  <ul class="menu">
   <li><a href="/georgeandrews1">Home</a></li>
   <li><a href="teaching.html">Teaching</a></li>
   <li><a href="contact.html">Contact</a></li>
   <li><a href="talks/Talks 2021.pdf">2021 Talks</a></li>
   <li><a href="talkvideos.html">Talk Videos</a></li>
   <li><a href="vitae.html">Curriculum Vitae</a></li>
   <li><a href="publications.html">List of Publications</a></li>
   <li><a href="preprints.html">Preprints</a></li>
   <li><a href="education.html">Math Education</a></li>
   <li><a href="http://www.pnas.org/cgi/content/full/102/13/4663">Biography (PNAS)</a></li>
   <li><a href="Drowning.pdf">AMS Retiring Presidential Address, "Drowning in the Data Deluge"</a></li>
   <li><a href="http://www.youtube.com/embed/GfXhgGURCxQ">Father and Son</a></li>
   <li><a href="http://www.collegian.psu.edu/news/campus/article_e69760e2-9f9e-11e5-aef8-c35f65f00249.html">2015 Collegian Article</a></li>
  <li><a href="https://amathr.org/">Association for Mathematical Research</a></li>
 </ul>

